name: Vulnerability Scan

on:
  schedule:
    - cron: '59 11 * * *'

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker pull habbdt/ibmcloud-cli:2.3.0

      - uses: lazy-actions/gitrivy@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          image: habbdt/ibmcloud-cli:2.3.0
          severity: HIGH,CRITICAL
          issue_title: IBM Cloud Cli Docker Image Security Issues
          issue_label: trivy,vulnerability,ibmcloud-cli:2.3.0
          issue_assignee: habbdt@gmail.com
